In [1]:
import surprise
import implicit

In [4]:
def factorial(n):
    res = 1
    for i in range(1, n+1):
        res *= i
    return res
factorial(5)

120

In [12]:
def combination(n,r):
    return factorial(n)/(factorial(r)*factorial(n-r))
combination(5,3)

10.0

In [13]:
import pandas as pd
import numpy as np

In [14]:
df = pd.read_csv('./data/house_prices.csv')

In [17]:
df.head(3)

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   

        B  LSTAT  MEDV  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7

In [18]:
df.iloc[2,4] + df.iloc[3,5]

7.4670000000000005

In [19]:
df.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV'],
      dtype='object')

In [22]:
X = df[df.columns[:5]]
X

CRIM    ZN  INDUS  CHAS    NOX
0    0.00632  18.0   2.31     0  0.538
1    0.02731   0.0   7.07     0  0.469
2    0.02729   0.0   7.07     0  0.469
3    0.03237   0.0   2.18     0  0.458
4    0.06905   0.0   2.18     0  0.458
..       ...   ...    ...   ...    ...
501  0.06263   0.0  11.93     0  0.573
502  0.04527   0.0  11.93     0  0.573
503  0.06076   0.0  11.93     0  0.573
504  0.10959   0.0  11.93     0  0.573
505  0.04741   0.0  11.93     0  0.573

[506 rows x 5 columns]

In [25]:
X_t = np.transpose(X)

In [27]:
XtX = X_t.dot(X) # 공분산

In [28]:
np.linalg.det(XtX)

5.318697879179408e+17

In [29]:
XtX_inv = np.linalg.inv(XtX)

In [30]:
XtX.dot(XtX_inv)

0             1             2             3             4
CRIM   1.000000e+00  1.802548e-17 -2.058407e-16  3.310259e-17  6.488672e-15
ZN     3.876846e-18  1.000000e+00  3.549498e-17 -1.178236e-15 -3.597749e-14
INDUS -1.205305e-16  7.856346e-17  1.000000e+00 -2.032484e-15  1.207309e-14
CHAS  -3.705449e-19 -1.512685e-19 -8.167007e-18  1.000000e+00  2.775057e-16
NOX   -1.017577e-17  2.147685e-18  5.254621e-18  7.186007e-17  1.000000e+00

In [33]:
np.inner(df['CRIM'], df['NOX'])

1226.1231702310001

In [35]:
conv_x = X_t.dot(X)
conv_x

CRIM            ZN         INDUS       CHAS         NOX
CRIM   43970.343555     468.70266  32479.095184   64.80846  1226.12317
ZN       468.702660  340029.00000  20903.090000  270.00000  2484.44175
INDUS  32479.095184   20903.09000  86525.629900  445.17000  3432.39536
CHAS      64.808460     270.00000    445.170000   35.00000    20.76990
NOX     1226.123170    2484.44175   3432.395360   20.76990   162.47038

In [36]:
e, v = np.linalg.eig(conv_x)

In [37]:
e

array([3.41796942e+05, 1.02737970e+05, 2.61371298e+04, 3.26583074e+01,
       1.77441256e+01])

In [39]:
v

array([[ 1.06600530e-02,  4.82019000e-01, -8.76089936e-01,
         3.21746923e-03,  3.45180803e-04],
       [ 9.96453844e-01, -7.81206913e-02, -3.08630034e-02,
        -1.15089670e-03, -4.80050958e-03],
       [ 8.30624537e-02,  8.72036354e-01,  4.80740696e-01,
        -1.19812261e-02, -3.73906326e-02],
       [ 8.97931896e-04,  3.88535216e-03,  5.71982320e-03,
         9.88567280e-01, -1.50619104e-01],
       [ 8.11927405e-03,  3.30506078e-02,  1.92240992e-02,
         1.50264788e-01,  9.87872797e-01]])

In [41]:
u, s, vt = np.linalg.svd(conv_x)

In [42]:
u

array([[-1.06600530e-02,  4.82019000e-01,  8.76089936e-01,
        -3.21746923e-03,  3.45180803e-04],
       [-9.96453844e-01, -7.81206913e-02,  3.08630034e-02,
         1.15089670e-03, -4.80050958e-03],
       [-8.30624537e-02,  8.72036354e-01, -4.80740696e-01,
         1.19812261e-02, -3.73906326e-02],
       [-8.97931896e-04,  3.88535216e-03, -5.71982320e-03,
        -9.88567280e-01, -1.50619104e-01],
       [-8.11927405e-03,  3.30506078e-02, -1.92240992e-02,
        -1.50264788e-01,  9.87872797e-01]])

In [43]:
s

array([3.41796942e+05, 1.02737970e+05, 2.61371298e+04, 3.26583074e+01,
       1.77441256e+01])

In [44]:
vt

array([[-1.06600530e-02, -9.96453844e-01, -8.30624537e-02,
        -8.97931896e-04, -8.11927405e-03],
       [ 4.82019000e-01, -7.81206913e-02,  8.72036354e-01,
         3.88535216e-03,  3.30506078e-02],
       [ 8.76089936e-01,  3.08630034e-02, -4.80740696e-01,
        -5.71982320e-03, -1.92240992e-02],
       [-3.21746923e-03,  1.15089670e-03,  1.19812261e-02,
        -9.88567280e-01, -1.50264788e-01],
       [ 3.45180803e-04, -4.80050958e-03, -3.73906326e-02,
        -1.50619104e-01,  9.87872797e-01]])

In [45]:
u2,s2,vt2 = np.linalg.svd(X)

In [46]:
u2

array([[-0.03101509,  0.00196257,  0.00346251, ..., -0.00242585,
        -0.00265735, -0.00236255],
       [-0.00101149,  0.01932427,  0.0209311 , ..., -0.00245423,
        -0.0024579 , -0.00245323],
       [-0.00101149,  0.01932424,  0.02093121, ..., -0.04883048,
        -0.04868345, -0.04887067],
       ...,
       [-0.00170403,  0.03260754,  0.03521387, ...,  0.99701042,
        -0.00298235, -0.00299156],
       [-0.00170492,  0.03268098,  0.03494926, ..., -0.00298271,
         0.99702445, -0.00298466],
       [-0.00170379,  0.03258747,  0.03528622, ..., -0.00299146,
        -0.00298421,  0.99700656]])

In [47]:
s2

array([584.63402402, 320.52764236, 161.66981734,   5.71474474,
         4.21237766])

In [48]:
vt2

array([[-1.06600530e-02, -9.96453844e-01, -8.30624537e-02,
        -8.97931896e-04, -8.11927405e-03],
       [ 4.82019000e-01, -7.81206913e-02,  8.72036354e-01,
         3.88535216e-03,  3.30506078e-02],
       [-8.76089936e-01, -3.08630034e-02,  4.80740696e-01,
         5.71982320e-03,  1.92240992e-02],
       [-3.21746923e-03,  1.15089670e-03,  1.19812261e-02,
        -9.88567280e-01, -1.50264788e-01],
       [-3.45180803e-04,  4.80050958e-03,  3.73906326e-02,
         1.50619104e-01, -9.87872797e-01]])

In [49]:
np.square(s2)

array([3.41796942e+05, 1.02737970e+05, 2.61371298e+04, 3.26583074e+01,
       1.77441256e+01])