## Numpy

### 1. Numpy Array and Operation

- numpy의 기본적인 사용법에 대해서 배워봅니다.


- numpy에서 numpy.array를 만드는 여러가지 방법과 지원하는 연산자에 대해서 공부합니다.

### 1.1. Numpy Array creation

In [2]:
# numpy 라이브러리를 불러옵니다.
import numpy as np

In [ ]:
# 파이썬 리스트 선언


In [ ]:
# 파이썬 2차원 리스트(행렬) 선언
data2 = 

In [ ]:
# 파이썬 list를 numpy array로 변환합니다.

# numpy array를 만드는 방식의 대부분은 파이썬 리스트를 np.array로 변환하는 방식입니다.


In [ ]:
# 2차원 리스트를 np.array로 만듭니다.
arr2 = np.array(data2) # data2라는 리스트를 numpy array로 만들어라.


In [ ]:
# 0부터 9까지 숫자를 자동으로 생성한 array
np.arange(0, 10)
np.zeros(5)
np.ones(7)
np.empty(3)  # uninitialized
np.linspace(0, 50, 50)

In [ ]:
# 10부터 99까지 숫자를 자동으로 생성한 array


### 1.2. Array Arithmetic (like vector)

In [ ]:
# v1 = (1, 2, 3), v2 = (4, 5, 6) 벡터 2개 생성하기.
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

In [ ]:
# 리스트로 더하기 연산해보기
L = [1, 2, 3]
L2 = [4, 5, 6]
L + L2

In [ ]:
#  vector addition


In [ ]:
#  vector subtraction


In [ ]:
# (not vector operation) elementwise multiplication


In [ ]:
# (not vector operation) elementwise division


In [ ]:
# dot product


### 1.3. Broadcast and Universal Function

- 서로 크기가 다른 numpy array를 연산할 때, 자동으로 연산을 전파(broadcast)해주는 기능. 행렬곱 연산을 할 때 편리하다.

In [ ]:
arr1 = np.array([1, 0, 0])

In [ ]:
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [ ]:
# 2개의 array를 더해보면?


In [ ]:
# 2개의 array를 곱해보면?


- Universal Function : broadcast 기능을 확장해서, numpy array의 모든 원소에 동일한 함수를 반복문으로 적용한 것과 같은 효과를 내는 기능.

In [ ]:
# f = lambda x : 1/x


In [ ]:
# f = lambda x : x + 2


### 1.4. Fancy Indexing 

- Numpy array는 list의 indexing을 확장하여 다양한 조건에서의 indexing을 지원한다.

- 주어진 numpy array를 통해서 여러가지 상황의 데이터를 추출하는 것을 연습해보자.

- 이 indexing은 pandas에서 확장되어 사용되니 꼭 익혀보자!


In [ ]:
arr1 = np.arange(10)

In [ ]:
# 첫번째 원소


In [ ]:
# 마지막 원소


In [ ]:
# 앞에서부터 원소 3개 slicing


In [3]:
arr2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# arr2의 2row, 3column 원소 = 7


In [ ]:
# arr2의 세번째 column [3, 7, 11]


In [ ]:
# arr2의 두번째 row


In [ ]:
# arr2에서 두번째 row중에서 6보다 큰 원소들 찾기

In [8]:
# arr2의 두번째 column중에서 6보다 큰 원소들 찾기
mask = arr2[:, 1]>6
arr2[:, 1][mask]

array([10])

In [16]:
arr2[arr2[:,1]>6,1]

array([10])

In [13]:
arr2[[False,False,True]]

array([[ 9, 10, 11, 12]])

In [10]:
arr2[0]

array([1, 2, 3, 4])

In [11]:
arr2[[0]]

array([[1, 2, 3, 4]])

In [19]:
4.1%3

1.0999999999999996

In [17]:
arr2[0:1]

array([[1, 2, 3, 4]])

## 2. Numpy Methods

- numpy에서 사용되는 여러가지 함수들을 사용해봅시다.

### 2.1. Math Functions 

In [24]:
# 표준정규분포에서 random sampling을 한 원소를 가지는 5x3 행렬을 만든다.
np.random.seed(42)
mat1 = np.random.randn(5, 3)
mat1

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473, -0.46947439],
       [ 0.54256004, -0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024, -1.72491783]])

In [26]:
# mat1에 절대값 씌우기
np.abs(mat1)

array([[0.49671415, 0.1382643 , 0.64768854],
       [1.52302986, 0.23415337, 0.23413696],
       [1.57921282, 0.76743473, 0.46947439],
       [0.54256004, 0.46341769, 0.46572975],
       [0.24196227, 1.91328024, 1.72491783]])

In [28]:
# mat1 제곱하기
np.square(mat1)

array([[0.24672495, 0.01911702, 0.41950044],
       [2.31961994, 0.0548278 , 0.05482011],
       [2.49391312, 0.58895606, 0.2204062 ],
       [0.2943714 , 0.21475596, 0.2169042 ],
       [0.05854574, 3.66064129, 2.97534153]])

In [30]:
# mat1의 제곱근 구하기
np.sqrt(np.square(mat1))

array([[0.49671415, 0.1382643 , 0.64768854],
       [1.52302986, 0.23415337, 0.23413696],
       [1.57921282, 0.76743473, 0.46947439],
       [0.54256004, 0.46341769, 0.46572975],
       [0.24196227, 1.91328024, 1.72491783]])

In [34]:
# linear algebra functions
vec = np.array([1,0,1])
mat = np.array([[1,0],[0,1]])

# 1. norm
print(np.linalg.norm(vec))

# 2. eigenvalue
print(np.linalg.eig(mat))

1.4142135623730951
EigResult(eigenvalues=array([1., 1.]), eigenvectors=array([[1., 0.],
       [0., 1.]]))


### 2.2. Aggregation functions 

In [35]:
np.random.seed(42) # seed set  ## reproducibility
mat2 = np.random.rand(3, 2)
mat2

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848],
       [0.15601864, 0.15599452]])

In [36]:
# Summation
np.sum(mat2)

2.9679200120443596

In [39]:
np.sum(mat2, axis=0)

array([1.2625527 , 1.70536731])

In [40]:
np.sum(mat2, axis=1)

array([1.32525443, 1.33065243, 0.31201316])

In [37]:
# mean
np.mean(mat2, axis=0)

array([0.4208509 , 0.56845577])

In [ ]:
# std
np.std(mat2)

In [43]:
mat2

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848],
       [0.15601864, 0.15599452]])

In [41]:
# min, max
np.min(mat2, axis=1)
#np.max(mat2, axis=0)

array([0.37454012, 0.59865848, 0.15599452])

In [44]:
np.min(mat2, axis=0)

array([0.15601864, 0.15599452])

In [45]:
np.min(mat2)

0.15599452033620265

In [42]:
# 최소값이 있는 Index
np.argmin(mat2, axis=1)

array([0, 1, 1], dtype=int64)

In [46]:
np.max(mat2, axis=0)

array([0.73199394, 0.95071431])

In [47]:
# 최대값이 있는 Index
np.argmax(mat2, axis=0)

array([1, 0], dtype=int64)

In [49]:
mat2

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848],
       [0.15601864, 0.15599452]])

In [48]:
# 그냥 정렬 (오름차순 정렬만 지원합니다)
np.sort(mat2, axis=0)

array([[0.15601864, 0.15599452],
       [0.37454012, 0.59865848],
       [0.73199394, 0.95071431]])

In [1]:
# index를 정렬
np.argsort(mat2, axis=0) # 정렬을 하고 난 결과의 원본 데이터 index를 출력

NameError: name 'np' is not defined

## 3. Performance Check

- Universal Function 기능을 통해 반복문을 사용한 것보다 훨씬 빠른 성능을 냅니다.


- 직접 실험을 통해 그 차이를 확인해보겠습니다.

In [51]:
def reverse_num(L):
    """
    reverse all values in list L
    """

    for i in range(len(L)):
        L[i] = 1 / L[i]

In [52]:
np.random.seed(0)

def np_reverse_num(values):
    output = np.empty(len(values))
    
    for i in range(len(values)):
        output[i] = 1.0 / values[i]

In [53]:
# 1부터 100까지 범위에서 1000000개를 랜덤으로 뽑아서 array를 만듭니다.
big_array = np.random.randint(1, 101, 1000000)
big_list = list(big_array)
print(big_array.shape, len(big_list))

(1000000,) 1000000


In [54]:
%timeit reverse_num(big_list)

142 ms ± 4.87 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [55]:
%timeit np_reverse_num(big_array)

1.96 s ± 47.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [56]:
%timeit 1 / big_array

4.2 ms ± 297 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
